name: cruxgarden

services:
  # Database Migrations (runs once before API starts)
  # Requires external DATABASE_URL
  migrations:
    image: ghcr.io/cruxgarden/api:latest
    container_name: cruxgarden-migrations
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    command: ["npm", "run", "migrate:prod"]
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Crux Garden API - Production Configuration
  # Requires external DATABASE_URL and REDIS_URL
  api:
    image: ghcr.io/cruxgarden/api:latest
    container_name: cruxgarden-api
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Application
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      BASE_URL: ${BASE_URL}

      # External Services (REQUIRED)
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

      # Security (REQUIRED)
      JWT_SECRET: ${JWT_SECRET}

      # AWS SES (REQUIRED)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_SES_FROM_EMAIL: ${AWS_SES_FROM_EMAIL}
      AWS_S3_ATTACHMENTS_BUCKET: ${AWS_S3_ATTACHMENTS_BUCKET:-crux-garden-attachments}

      # Optional Configuration
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DB_POOL_MIN: ${DB_POOL_MIN:-2}
      DB_POOL_MAX: ${DB_POOL_MAX:-10}
      DB_POOL_IDLE_TIMEOUT: ${DB_POOL_IDLE_TIMEOUT:-30000}
      DB_POOL_ACQUIRE_TIMEOUT: ${DB_POOL_ACQUIRE_TIMEOUT:-60000}
      RATE_LIMIT_TTL: ${RATE_LIMIT_TTL:-60000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
