import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    const authorId = 'e7f5c645-6b4e-4c3b-a5cb-3fd81c652b96';

    // Look up the primary home
    const primaryHome = await knex("homes")
        .where({ primary: true })
        .whereNull('deleted')
        .first();

    if (!primaryHome) {
        throw new Error('Primary home not found. Run common seeds first.');
    }

    // Fixed IDs for demo cruxes (matching production data)
    const cruxIds = {
        keeperRoot: 'f7f5c645-6b4e-4c3b-a5cb-3fd81c652b96', // Created in common seeds
        whatIsCruxGarden: 'be464476-892a-40f5-b26b-ee340f060c72',
        theGateDimension: 'e350f0df-50b1-421f-8e13-9debf1b7a676',
        theGardenDimension: '5c30f5d4-2fb3-4b1d-9c12-c478d0f7f574',
        theGrowthDimension: 'c5b894f6-2957-4b99-9008-8cbe69851ea7',
        theGraftDimension: 'ba08730b-bca3-43cb-a485-ed00f3b46c27',
        // Gate examples (origins/inspirations)
        theMemex: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
        digitalGardens: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
        graphDatabases: 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
        interactiveFiction: 'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
        // Garden examples (creations/consequences)
        researchProjects: 'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b',
        interactiveStories: 'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
        livingDocumentation: 'a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d',
        collaborativeWorlds: 'b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e',
        // Growth examples (evolution)
        originalConcept: 'c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f',
        discoveryOfFourDimensions: 'd0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a',
        fractalRealization: 'e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b',
        mediumForImagination: 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c',
        // Graft examples (associations)
        toolsForThought: 'a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d',
        pkm: 'b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e',
        zettelkasten: 'c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f',
        collectiveIntelligence: 'd6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a',
    };

    // Demo cruxes for the nursery environment
    // Note: Keeper root crux is created in common seeds, we just reference it
    const demoCruxes = [
        {
            id: cruxIds.whatIsCruxGarden,
            key: 'x5cePKOMDLtq4VGP',
            slug: 'what-is-crux-garden',
            title: 'What is Crux Garden?',
            description: null,
            data: 'Crux Garden is a model of how ideas manifest and develop over time. The heart of the model is the Crux, an atomic representation of an idea. In our implementation, a crux can be text, media, code, or any digital content worth preserving. But cruxes, just like ideas, don\'t exist in isolation. Ideas have origins. They lead to new ideas. They evolve. And often, they randomly connect. So it is with cruxes. In Crux Garden, there are four types of relationships cruxes can have with each other. These are called Dimensions.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T00:08:39.765Z'),
            updated: new Date('2025-10-15T02:32:43.042Z'),
        },
        {
            id: cruxIds.theGateDimension,
            key: '6JkpJQhNXN1BfNZ0',
            slug: 'the-gate-dimension',
            title: 'The Gate Dimension',
            description: null,
            data: 'Gates are cruxes which influenced or inspired a crux; its origins and sources.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:02:42.413Z'),
            updated: new Date('2025-10-15T02:32:00.956Z'),
        },
        {
            id: cruxIds.theGardenDimension,
            key: 'q-f42iFP9NN--m4j',
            slug: 'the-garden-dimension',
            title: 'The Garden Dimension',
            description: null,
            data: 'Gardens are cruxes which emerged or grew from a crux, its creations and consequences.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:03:51.974Z'),
            updated: new Date('2025-10-15T02:03:51.974Z'),
        },
        {
            id: cruxIds.theGrowthDimension,
            key: 'qMLz86MestQUfIaf',
            slug: 'the-growth-dimension',
            title: 'The Growth Dimension',
            description: null,
            data: 'Growth is how a crux developed over time, its transformation and refinement.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:04:38.840Z'),
            updated: new Date('2025-10-15T02:04:38.840Z'),
        },
        {
            id: cruxIds.theGraftDimension,
            key: '4Vtt0OtmKzzZEtYW',
            slug: 'the-graft-dimension',
            title: 'The Graft Dimension',
            description: null,
            data: 'Grafts are cruxes which connect to a crux laterally, its associations and resonances.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:11:33.307Z'),
            updated: new Date('2025-10-15T02:11:33.307Z'),
        },
        // Gate examples
        {
            id: cruxIds.theMemex,
            key: 'M3m3xBush1945VB',
            slug: 'the-memex',
            title: 'The Memex (1945)',
            description: 'Vannevar Bush\'s vision of associative memory',
            data: 'In 1945, Vannevar Bush imagined the Memex - a device where knowledge could grow through associative trails. It was a proto-hypertext system where scholars could create their own paths through information, building connections that reflected their thinking process rather than rigid categorization.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:00:00.000Z'),
            updated: new Date('2025-10-16T00:00:00.000Z'),
        },
        {
            id: cruxIds.digitalGardens,
            key: 'D1g1talGard3n5MV',
            slug: 'digital-gardens-movement',
            title: 'Digital Gardens Movement',
            description: 'Growing ideas in public',
            data: 'Digital gardens are spaces for cultivating ideas in public. Unlike blogs with their reverse-chronological feeds, gardens are organized by connection and topic. They grow organically, with ideas at different stages of growth existing side by side. Some notes are seedlings, others are evergreen.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:01:00.000Z'),
            updated: new Date('2025-10-16T00:01:00.000Z'),
        },
        {
            id: cruxIds.graphDatabases,
            key: 'GraphDb5N3o4jCyph',
            slug: 'graph-databases',
            title: 'Graph Databases',
            description: 'Storing relationships as first-class citizens',
            data: 'Graph databases like Neo4j treat relationships between entities as first-class data, not just foreign keys. This makes them ideal for knowledge networks, social graphs, and any domain where connections are as important as the nodes themselves. The structure mirrors how we naturally think about connected information.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:02:00.000Z'),
            updated: new Date('2025-10-16T00:02:00.000Z'),
        },
        {
            id: cruxIds.interactiveFiction,
            key: 'Int3ract1v3F1ct10n',
            slug: 'interactive-fiction',
            title: 'Interactive Fiction',
            description: 'Stories where readers make choices',
            data: 'Interactive fiction, from text adventures to choice-driven narratives, demonstrates how meaning emerges from traversing connected nodes. Each decision creates a unique path through the story space. The same content becomes different experiences based on the route taken.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:03:00.000Z'),
            updated: new Date('2025-10-16T00:03:00.000Z'),
        },
        // Garden examples
        {
            id: cruxIds.researchProjects,
            key: 'R3s3archPr0j3cts',
            slug: 'research-projects',
            title: 'Research Projects',
            description: 'Connected knowledge that evolves',
            data: 'Research projects benefit from Crux Garden\'s structure. Start with a question. Add sources as gates. Create synthesis notes as gardens. Track how your thinking evolved through growth. Link to related work via grafts. The result is a living research artifact that shows not just conclusions but the journey.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:04:00.000Z'),
            updated: new Date('2025-10-16T00:04:00.000Z'),
        },
        {
            id: cruxIds.interactiveStories,
            key: 'Int3ract1v3St0r13s',
            slug: 'interactive-stories',
            title: 'Interactive Stories',
            description: 'Narrative experiences with branching paths',
            data: 'Interactive stories in Crux Garden use dimensions to create choice-driven narratives. Each story crux can have multiple garden dimensions representing possible next scenes. Gates show what led to this moment. Growth tracks how the story evolved during creation. The result is a narrative that readers explore rather than consume.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:05:00.000Z'),
            updated: new Date('2025-10-16T00:05:00.000Z'),
        },
        {
            id: cruxIds.livingDocumentation,
            key: 'L1v1ngD0cum3ntat1on',
            slug: 'living-documentation',
            title: 'Living Documentation',
            description: 'Documentation that grows with your project',
            data: 'Living documentation in Crux Garden evolves alongside your project. Each concept is a crux. Technical decisions link to their requirements (gates) and implementations (gardens). When requirements change, update the crux and see what\'s affected. Documentation becomes a living map of your system.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:06:00.000Z'),
            updated: new Date('2025-10-16T00:06:00.000Z'),
        },
        {
            id: cruxIds.collaborativeWorlds,
            key: 'C0llab0rat1v3W0rlds',
            slug: 'collaborative-worlds',
            title: 'Collaborative Worlds',
            description: 'Shared universes built together',
            data: 'Collaborative worlds emerge when multiple creators contribute connected cruxes. One person establishes lore (gates). Another adds a location (garden). Someone expands on the timeline (growth). Others find parallels in different parts of the world (grafts). The result is a shared universe richer than any individual could create.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:07:00.000Z'),
            updated: new Date('2025-10-16T00:07:00.000Z'),
        },
        // Growth examples
        {
            id: cruxIds.originalConcept,
            key: '0r1g1nalC0nc3ptSt0ry',
            slug: 'original-concept',
            title: 'Original Concept: Storytelling',
            description: 'Where Crux Garden began',
            data: 'Crux Garden started as a tool for interactive storytelling. The initial vision was simple: let authors create branching narratives where readers could explore different paths. Each story beat was a crux, and choices led to new cruxes. It was about narrative, not knowledge.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:08:00.000Z'),
            updated: new Date('2025-10-16T00:08:00.000Z'),
        },
        {
            id: cruxIds.discoveryOfFourDimensions,
            key: 'D1sc0v3ry4D1m3ns10ns',
            slug: 'discovery-of-four-dimensions',
            title: 'Discovery of Four Dimensions',
            description: 'Realizing all relationships have types',
            data: 'The breakthrough came when we realized not all connections are the same. A story crux leading to the next scene (garden) is fundamentally different from a crux referencing its inspiration (gate). Tracking revisions (growth) is different from noting similarities (graft). Four dimensions emerged as sufficient to model any relationship between ideas.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:09:00.000Z'),
            updated: new Date('2025-10-16T00:09:00.000Z'),
        },
        {
            id: cruxIds.fractalRealization,
            key: 'Fract4lR3al1zat10n',
            slug: 'fractal-realization',
            title: 'Fractal Realization',
            description: 'The model scales infinitely',
            data: 'The fractal nature of Crux Garden means the same four-dimensional model works at every scale. A sentence is a crux. A paragraph is a crux. A document is a crux. A whole project is a crux. The relationships between them use the same dimensions. Simple rules, infinite complexity.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:10:00.000Z'),
            updated: new Date('2025-10-16T00:10:00.000Z'),
        },
        {
            id: cruxIds.mediumForImagination,
            key: 'M3d1umF0rImag1nat10n',
            slug: 'medium-for-imagination',
            title: 'Medium for Imagination',
            description: 'The current vision',
            data: 'Crux Garden has evolved beyond storytelling into a medium for imagination itself. It\'s infrastructure for how ideas live and grow in the digital age. Whether you\'re building research, stories, documentation, or worlds - the four dimensions provide a universal language for connected thought.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:11:00.000Z'),
            updated: new Date('2025-10-16T00:11:00.000Z'),
        },
        // Graft examples
        {
            id: cruxIds.toolsForThought,
            key: 'T00lsF0rTh0ughtMvt',
            slug: 'tools-for-thought',
            title: 'Tools for Thought Movement',
            description: 'Software that augments thinking',
            data: 'The Tools for Thought movement explores how software can augment human cognition. From early systems like Engelbart\'s NLS to modern tools like Roam and Obsidian, the goal is software that helps us think better, not just store information. Crux Garden is part of this tradition.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:12:00.000Z'),
            updated: new Date('2025-10-16T00:12:00.000Z'),
        },
        {
            id: cruxIds.pkm,
            key: 'P3rs0nalKn0wl3dg3Mgt',
            slug: 'personal-knowledge-management',
            title: 'Personal Knowledge Management',
            description: 'Systems for organizing what you learn',
            data: 'Personal Knowledge Management (PKM) is about building systems to capture, organize, and retrieve what you learn. The goal isn\'t just storage - it\'s creating a personal library that helps you think. Crux Garden provides structure for PKM through its four dimensions.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:13:00.000Z'),
            updated: new Date('2025-10-16T00:13:00.000Z'),
        },
        {
            id: cruxIds.zettelkasten,
            key: 'Z3tt3lkast3nM3th0d',
            slug: 'zettelkasten-method',
            title: 'Zettelkasten Method',
            description: 'The slip-box system',
            data: 'Zettelkasten (German for "slip-box") is a method where atomic notes link to each other, forming a web of knowledge. Each note has one idea. Notes link to related notes. Over time, clusters emerge around topics. Crux Garden\'s atomic cruxes and typed dimensions are a digital evolution of this method.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:14:00.000Z'),
            updated: new Date('2025-10-16T00:14:00.000Z'),
        },
        {
            id: cruxIds.collectiveIntelligence,
            key: 'C0ll3ct1v3Int3ll1g3nc3',
            slug: 'collective-intelligence',
            title: 'Collective Intelligence',
            description: 'Thinking together',
            data: 'Collective intelligence emerges when groups think together effectively. Wikipedia, open-source software, and scientific collaboration all demonstrate how connected individuals create knowledge no one person could produce alone. Crux Garden enables this by making individual gardens connect into an ecosystem.',
            type: 'markdown',
            status: 'living',
            visibility: 'unlisted',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:15:00.000Z'),
            updated: new Date('2025-10-16T00:15:00.000Z'),
        },
    ];

    // Check each crux and only insert if it doesn't exist
    for (const crux of demoCruxes) {
        const existing = await knex("cruxes")
            .where({ key: crux.key })
            .first();

        if (!existing) {
            await knex("cruxes").insert(crux);
        }
    }

    // Dimensions connecting the cruxes
    const demoDimensions = [
        {
            id: '3d248351-8c39-4bed-9c09-fd7aa26a4fce',
            key: '-YJW6HbzsPIFg5LT',
            source_id: cruxIds.keeperRoot,
            target_id: cruxIds.whatIsCruxGarden,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T00:08:39.787Z'),
            updated: new Date('2025-10-15T00:08:39.787Z'),
        },
        {
            id: '419ffdad-c43a-4b86-a44c-2fd069e93e55',
            key: '-Vvo42QGdKQ-5gst',
            source_id: cruxIds.whatIsCruxGarden,
            target_id: cruxIds.theGateDimension,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:02:42.433Z'),
            updated: new Date('2025-10-15T02:02:42.433Z'),
        },
        {
            id: '535c1cf8-ad2a-4523-aba9-6e059414e290',
            key: 'mpkTND2M6K4aoYkX',
            source_id: cruxIds.whatIsCruxGarden,
            target_id: cruxIds.theGardenDimension,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:03:51.990Z'),
            updated: new Date('2025-10-15T02:03:51.990Z'),
        },
        {
            id: '7b2d3451-e8e0-480c-931f-03ec1644e03f',
            key: 'iZnSwslMQ1Ufw4fw',
            source_id: cruxIds.whatIsCruxGarden,
            target_id: cruxIds.theGrowthDimension,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:04:38.862Z'),
            updated: new Date('2025-10-15T02:04:38.862Z'),
        },
        {
            id: '9848697d-17a8-4612-9f51-2df2aae69367',
            key: 'F0ZCJEW9Gl7mjAI5',
            source_id: cruxIds.whatIsCruxGarden,
            target_id: cruxIds.theGraftDimension,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-15T02:11:33.322Z'),
            updated: new Date('2025-10-15T02:11:33.322Z'),
        },
        // Gate examples - connect from "The Gate Dimension" to demonstrate gate relationships
        {
            id: 'a1111111-1111-1111-1111-111111111111',
            key: 'gat3Mem3xExampl3',
            source_id: cruxIds.theGateDimension,
            target_id: cruxIds.theMemex,
            type: 'gate',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:20:00.000Z'),
            updated: new Date('2025-10-16T00:20:00.000Z'),
        },
        {
            id: 'a2222222-2222-2222-2222-222222222222',
            key: 'gat3D1g1talGard3n',
            source_id: cruxIds.theGateDimension,
            target_id: cruxIds.digitalGardens,
            type: 'gate',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:21:00.000Z'),
            updated: new Date('2025-10-16T00:21:00.000Z'),
        },
        {
            id: 'a3333333-3333-3333-3333-333333333333',
            key: 'gat3GraphDbExampl3',
            source_id: cruxIds.theGateDimension,
            target_id: cruxIds.graphDatabases,
            type: 'gate',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:22:00.000Z'),
            updated: new Date('2025-10-16T00:22:00.000Z'),
        },
        {
            id: 'a4444444-4444-4444-4444-444444444444',
            key: 'gat3Int3ract1v3F1c',
            source_id: cruxIds.theGateDimension,
            target_id: cruxIds.interactiveFiction,
            type: 'gate',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:23:00.000Z'),
            updated: new Date('2025-10-16T00:23:00.000Z'),
        },
        // Garden examples - connect from "The Garden Dimension" to demonstrate garden relationships
        {
            id: 'b1111111-1111-1111-1111-111111111111',
            key: 'gard3nR3s3archPrj',
            source_id: cruxIds.theGardenDimension,
            target_id: cruxIds.researchProjects,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:24:00.000Z'),
            updated: new Date('2025-10-16T00:24:00.000Z'),
        },
        {
            id: 'b2222222-2222-2222-2222-222222222222',
            key: 'gard3nInt3ractSt0ry',
            source_id: cruxIds.theGardenDimension,
            target_id: cruxIds.interactiveStories,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:25:00.000Z'),
            updated: new Date('2025-10-16T00:25:00.000Z'),
        },
        {
            id: 'b3333333-3333-3333-3333-333333333333',
            key: 'gard3nL1v1ngD0cs',
            source_id: cruxIds.theGardenDimension,
            target_id: cruxIds.livingDocumentation,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:26:00.000Z'),
            updated: new Date('2025-10-16T00:26:00.000Z'),
        },
        {
            id: 'b4444444-4444-4444-4444-444444444444',
            key: 'gard3nC0llab0Wrlds',
            source_id: cruxIds.theGardenDimension,
            target_id: cruxIds.collaborativeWorlds,
            type: 'garden',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:27:00.000Z'),
            updated: new Date('2025-10-16T00:27:00.000Z'),
        },
        // Growth examples - connect showing evolution of Crux Garden concept
        {
            id: 'c1111111-1111-1111-1111-111111111111',
            key: 'gr0wth0r1g1nalC0nc3pt',
            source_id: cruxIds.whatIsCruxGarden,
            target_id: cruxIds.originalConcept,
            type: 'growth',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:28:00.000Z'),
            updated: new Date('2025-10-16T00:28:00.000Z'),
        },
        {
            id: 'c2222222-2222-2222-2222-222222222222',
            key: 'gr0wthD1sc0v3ry4D',
            source_id: cruxIds.originalConcept,
            target_id: cruxIds.discoveryOfFourDimensions,
            type: 'growth',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:29:00.000Z'),
            updated: new Date('2025-10-16T00:29:00.000Z'),
        },
        {
            id: 'c3333333-3333-3333-3333-333333333333',
            key: 'gr0wthFract4lR3al',
            source_id: cruxIds.discoveryOfFourDimensions,
            target_id: cruxIds.fractalRealization,
            type: 'growth',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:30:00.000Z'),
            updated: new Date('2025-10-16T00:30:00.000Z'),
        },
        {
            id: 'c4444444-4444-4444-4444-444444444444',
            key: 'gr0wthM3d1umImag',
            source_id: cruxIds.fractalRealization,
            target_id: cruxIds.mediumForImagination,
            type: 'growth',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:31:00.000Z'),
            updated: new Date('2025-10-16T00:31:00.000Z'),
        },
        // Graft examples - connect from "The Graft Dimension" to demonstrate graft relationships
        {
            id: 'd1111111-1111-1111-1111-111111111111',
            key: 'graftT00lsTh0ught',
            source_id: cruxIds.theGraftDimension,
            target_id: cruxIds.toolsForThought,
            type: 'graft',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:32:00.000Z'),
            updated: new Date('2025-10-16T00:32:00.000Z'),
        },
        {
            id: 'd2222222-2222-2222-2222-222222222222',
            key: 'graftPKMExampl3',
            source_id: cruxIds.theGraftDimension,
            target_id: cruxIds.pkm,
            type: 'graft',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:33:00.000Z'),
            updated: new Date('2025-10-16T00:33:00.000Z'),
        },
        {
            id: 'd3333333-3333-3333-3333-333333333333',
            key: 'graftZ3tt3lkast3n',
            source_id: cruxIds.theGraftDimension,
            target_id: cruxIds.zettelkasten,
            type: 'graft',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:34:00.000Z'),
            updated: new Date('2025-10-16T00:34:00.000Z'),
        },
        {
            id: 'd4444444-4444-4444-4444-444444444444',
            key: 'graftC0ll3ct1v3Int',
            source_id: cruxIds.theGraftDimension,
            target_id: cruxIds.collectiveIntelligence,
            type: 'graft',
            author_id: authorId,
            home_id: primaryHome.id,
            created: new Date('2025-10-16T00:35:00.000Z'),
            updated: new Date('2025-10-16T00:35:00.000Z'),
        },
    ];

    // Check each dimension and only insert if it doesn't exist
    for (const dimension of demoDimensions) {
        const existing = await knex("dimensions")
            .where({ key: dimension.key })
            .first();

        if (!existing) {
            await knex("dimensions").insert(dimension);
        }
    }
}
